### ISSUE TITLE
一个简单的登录搞的都登录不进去

### ISSUE THREAD

**Issue by cc0411** [pythonzm/Ops#11]
rsakey = RSA.importKey(key)  # 导入私钥
        cipher = PKCS1_v1_5.new(rsakey)  # 生成对象
        missing_padding = len(en_pwd) % 4
        if missing_padding:
            en_pwd += b'=' * (4 - missing_padding)
        text = cipher.decrypt(base64.b64decode(en_pwd.encode('utf-8')), "ERROR")  # 将密文解密成明文，返回的是一个bytes类型数据，需要自己转换成str

        return text.decode('utf-8')

**Comment by cc0411** [comment]
git reset 上次提交也无法登录 放弃

**Comment by pythonzm** [comment]
无法登录？具体报什么错？

**Comment by cc0411** [comment]
就报我发的那段代码有问题  不是byte  是str

**Comment by pythonzm** [comment]
感谢反馈，第一次做数据加密传输这块儿，所以可能会有点儿坑 @_@
