### ISSUE TITLE
能实现关闭浏览器后再找回ansible执行playbook的进度条么

### ISSUE THREAD

**Issue by NikelChamp** [pythonzm/Ops#13]
大佬，我看了channels文档，好像都是用来做聊天室之类的，想试着做找回进度条的功能，一点思路都没有，有什么能参考一下的么

**Comment by pythonzm** [comment]
1、比较简单的办法：在前端添加两个按钮，一个停止按钮，按下就停止前端界面的输出，一个开启按钮，按下就继续输出，整个过程websocket都没有断，只是选择是否把数据append到界面

2、比较麻烦的办法：也是两个按钮，一个停止按钮，按下就断开websocket，一个开启按钮，按下就重新连接websocket，这种办法需要将sock的输出同步输出到redis或其他中间件，重新打开websocket就重新从redis中拉取当前的输出内容

**Comment by pythonzm** [comment]
第一个办法不能关闭浏览器或者当前界面，第二个办法可以关闭

**Comment by NikelChamp** [comment]
能不能不设置停止按钮，关闭浏览器就中断websocket，再打开浏览器就重新连接websocket直接显示内容？

**Comment by pythonzm** [comment]
第二个方法可以不用按钮

**Comment by NikelChamp** [comment]
那websocket是不是需要另外用进程启动？

**Comment by NikelChamp** [comment]
webssh有时会出现出现连接不上的情况
all.log上记录的是
```
MySQL server has gone away (BrokenPipeError(32, 'Broken pipe')) ， 
```
报这个错误，有时候又是另一个错误
```
Lost connection to MySQL server
```
上网查说写入的数据太长，可是记录入表的部分字段也不长啊

**Comment by pythonzm** [comment]
> 那websocket是不是需要另外用进程启动？

恩，关闭浏览器之前的websocket就断开了，要重新连接就得重新开启websocket连接

**Comment by pythonzm** [comment]
> webssh有时会出现出现连接不上的情况
> all.log上记录的是
> 
> ```
> MySQL server has gone away (BrokenPipeError(32, 'Broken pipe')) ， 
> ```
> 报这个错误，有时候又是另一个错误
> 
> ```
> Lost connection to MySQL server
> ```
> 然后大部分情况是下面这个错误,
> 
> ```
> applicationCreateFailed [Failure instance: Traceback: <class 'django.db.utils.InterfaceError'>: (0, '')
> ```
> 排查了一下原因，是因为连接超过了mysql的wait_timeout设置的时长，感觉就像是程序一跑起来就连接了mysql, 这样是不是有点不合理，如果程序一直起着，mysql的连接总是会超时的，难道超时了又重启一下？

是Ops系统一跑起来就连接数据库还是webssh程序的问题？

**Comment by NikelChamp** [comment]
我觉得是系统一跑起来就连接数据库了，然后空闲时间超时被mysql断开了连接，按理说应该不会这样才对，这样就webssh对mysql做了长连接了，你可以试试看把wait_timeout设置短一点，启动程序后可以发现是能连接上的，断开后等过了wait_timeout设置的时间就会连接失败了

**Comment by pythonzm** [comment]
> 我觉得是系统一跑起来就连接数据库了，然后空闲时间超时被mysql断开了连接，按理说应该不会这样才对，这样就webssh对mysql做了长连接了，你可以试试看把wait_timeout设置短一点，启动程序后可以webssh发现是能连接上的，断开后等过了wait_timeout设置的时间就会连接失败了

确实有这问题，目前还没啥思路。。（＃－.－）

**Comment by NikelChamp** [comment]
我找到了解决方法了，一个大神弄的猴子补丁，可以pip安装的工具包，django_db_reconnect, 主要是维护MySQL的连接，[django-db-reconnect](https://github.com/zhanghaofei/django-db-reconnect/l)，我觉得可以参考一下

**Comment by pythonzm** [comment]
回头我试试，最近有点儿忙

**Comment by NikelChamp** [comment]
日程管理删除会报500, 好像middleware的判断有问题，会判断执行记录删除用户，把request.path里的user_plan.id当成了user_id，会出现检索错误
```
if 'users' in request.path:
    if ’plan_info‘ in request.path:
        pass
```
下面应该再加一个判断

**Comment by pythonzm** [comment]
感谢反馈 :)
