### ISSUE TITLE
makemigrations有报错，migrate提示ops_admin_record表已存在

### ISSUE THREAD

**Issue by vnline** [pythonzm/Ops#15]
(ops) [root@1Ops]# python manage.py makemigrations assets users dbmanager fort plan projs task wiki
You are trying to add a non-nullable field 'asset_admin' to assets without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> 22
You are trying to add a non-nullable field 'user' to assetslog without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> root
Invalid input: name 'root' is not defined
>>> 'root'
You are trying to add the field 'add_time' with 'auto_now_add=True' to userplan without a default; the database needs something to populate existing rows.

 1) Provide a one-off default now (will be set on all existing rows)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
You can accept the default 'timezone.now' by pressing 'Enter' or you can provide another value.
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
[default: timezone.now] >>> 
You are trying to add a non-nullable field 'content' to userplan without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> 'test'

(ops) [root@1 Ops]# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, assets, auth, contenttypes, dbmanager, django_celery_beat, django_celery_results, fort, projs, sessions, task, users, wiki
Running migrations:
  Applying assets.0002_auto_20190523_1448...Traceback (most recent call last):
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/data/miniconda/envs/ops/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1050, "Table 'ops_admin_record' already exists")

**Comment by pythonzm** [comment]
把数据库删了重新建，然后migrations的时候改一下顺序，python manage.py makemigrations users assets dbmanager fort plan projs task wiki
