### ISSUE TITLE
新建服务器类型资产，浏览器返回503

### ISSUE THREAD

**Issue by wpw303** [pythonzm/Ops#16]
你好，启动项目后新建服务器类型资产时，POST调用/api/servers_assets 的时候浏览器返回503，实际数据已经插入，通过直接访问/api/servers_assets,去post新建服务器资产也返回503，调试一天了，也没查到原因，请大神帮助下,非常感谢；

**Comment by pythonzm** [comment]
F12进console，浏览器有什么具体返回信息么？

**Comment by wpw303** [comment]
post :Status Code: 503 Service Unavailable. --这个就是浏览器返回的
console:
没有的返回信息。
难道是我的启动方式不对么，不是用 manage.py runserver 0.0.0.0:8000么？
另外是否不支持put请求，更新资产数据总是报 {
    "assets": {
        "asset_nu": [
            "总资产表 with this 资产编号 already exists."
        ]
    }
}

**Comment by pythonzm** [comment]
浏览器中Response返回的是什么？
更新资产的函数改过什么吗？

**Comment by wpw303** [comment]
不好意思，原因找到了 ，应该是没有启动celery，造成的
