### ISSUE TITLE
是否增加实时监控功能？

### ISSUE THREAD

**Issue by muse117** [pythonzm/Ops#22]
您好，请问您是否有考虑增加实时监控功能呢？我这段时间也在关注基于guacamole的实时监控，可否讨论一下思路呢？

**Comment by pythonzm** [comment]
暂时没考虑，本身不是一个专业的堡垒机，只是提供一些基本功能

**Comment by pythonzm** [comment]
@muse117 我没研究过guac，Windows的web端也是参考的这个大佬的https://github.com/jimmy201602/webterminal

**Comment by muse117** [comment]
> @muse117 我没研究过guac，Windows的web端也是参考的这个大佬的https://github.com/jimmy201602/webterminal

好的，谢谢了
