### ISSUE TITLE
大佬 我选择主机的时候 主机的选项跑到modal后面去了，挡住了

### ISSUE THREAD

**Issue by niehuan** [pythonzm/Ops#23]
![image](https://user-images.githubusercontent.com/43259265/61524730-a3dcc580-aa49-11e9-80b6-275a1ff927fd.png)

**Comment by pythonzm** [comment]
用谷歌浏览器试试

**Comment by niehuan** [comment]
> 用谷歌浏览器试试

就是用的谷歌浏览器，是不是前端哪儿的样式没有生效还是？我是只集成了你关于堡垒机那一部分功能，请教一下。

**Comment by pythonzm** [comment]
你看console里有没有报错
