### ISSUE TITLE
操作记录

### ISSUE THREAD

**Issue by LemWong** [pythonzm/Ops#3]
我在本地上运行这套系统，发现用户操作及资产操作记录这一块好像并没有记录，是这块功能没实现还是我操作不当呢？

**Comment by pythonzm** [comment]
> 我在本地上运行这套系统，发现用户操作及资产操作记录这一块好像并没有记录，是这块功能没实现还是我操作不当呢？

所有的操作记录都是通过celery异步入库的，看一下celery运行是否正常
