### ISSUE TITLE
日期类型错误

### ISSUE THREAD

**Issue by faer615** [pythonzm/Ops#32]
Applying assets.0002_auto_20190910_1755...Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
......
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'

**Comment by pythonzm** [comment]
这是做什么操作报的错？自己改什么了么

**Comment by faer615** [comment]
按照帮助文档操作的。系统是centos7.6，python3.6使用的epel的。

**Comment by pythonzm** [comment]
这是初始化表报的错么？试试把每个应用下的migrations下的文件都删除，只保留__init__.py文件，再重新初始化
