### ISSUE TITLE
上传文件失败

### ISSUE THREAD

**Issue by Fb19970305** [pythonzm/Ops#33]
我想请教一下，在资产管理模块下的资产列表页面，批量导入时，导入不成功，后端无法接收到导入的文件是什么原因，返回400。

**Comment by pythonzm** [comment]
是按照资产导入模板中的格式填写的内容么

**Comment by Fb19970305** [comment]
是的，我是先导出一份资产然后再导入，文件格式应该没有问题。问题是我在后端无法接收到上传的文件。

**Comment by pythonzm** [comment]
导出的文件不能直接导入，导入的话需要使用导入模板

**Comment by Fb19970305** [comment]
模板错误只是后续数据处理会有问题，我现在就是不知道为什么后端都无法接收到那个文件，不知道是不是代码哪里做了限制或者有些环境依赖有问题

**Comment by pythonzm** [comment]
有具体报错吗

**Comment by Fb19970305** [comment]
报400 bad request，类型是其它没有问题，就是上传文件有问题

**Comment by Fb19970305** [comment]
你好，问题我可以解决，在centos下没有问题，在ubuntu下会有问题，但原因未知。

**Comment by pythonzm** [comment]
ubuntu用的不多，帮不上忙了
