### ISSUE TITLE
能否实现ssh反向链接

### ISSUE THREAD

**Issue by Chise1** [pythonzm/Ops#35]
通过反向链接的方式，将用户端的ubuntu服务器连接到设备。

**Comment by pythonzm** [comment]
没太理解，能不能再通俗点儿，或者举个例子？

**Comment by Chise1** [comment]
举个例子，就是要连接的对象没有公网ip。需要内网服务器先tcp连接公网服务器，然后公网服务器反向ssh连接到内网服务器进行操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pythonzm"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 下午3:37
收件人:&nbsp;"pythonzm/Ops"<Ops@noreply.github.com&gt;;
抄送:&nbsp;"Chise1"<chise123@live.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pythonzm/Ops] 能否实现ssh反向链接 (#35)




没太理解，能不能再通俗点儿，或者举个例子？

**Comment by pythonzm** [comment]
这种情况倒没有想过，有时间研究一下

**Comment by pythonzm** [comment]
不知道你的问题现在解决了没有，我发现了一个不错的内网穿透的工具：[https://github.com/fatedier/frp](https://github.com/fatedier/frp)，我没有实验环境，而且目前也很少有这方面需求，所以不打算集成到这个项目里了，你可以试试这个工具

**Comment by Chise1** [comment]
多谢，不过我已经没搞这个了
