### ISSUE TITLE
能不能增加同一ip不同端口登录的功能

### ISSUE THREAD

**Issue by wardseptember** [pythonzm/Ops#44]
能不能增加同一ip不同端口登录的功能，这个功能很迫切，谢谢作者。

**Comment by pythonzm** [comment]
这种需求貌似不多吧，需要改的地方不是很多，把ServerAssets的port字段改成CharField，存端口的时候保存成固定格式，比如：22,23,24或22:23:24等分隔符一致的，这样好分割，添加主机的时候把这个port作为变量传给后台，然后再改webssh代码，把port改成前端接收到数据就行了

如果主机不多不用改也许，本身系统也没有做ip的非重复判定，直接同一个ip主机添加多次也可以的

**Comment by wardseptember** [comment]
@pythonzm 谢谢作者的回复。不仅仅是连接，包括任务管理、项目管理模块等功能都要实现，相当于实现不同ip主机添加后的所有功能。我对django不是很熟悉，尝试去修改，还是遇到很大的问题。希望作者空闲的时候能增加一下这个功能。
