### ISSUE TITLE
执行ansible脚本吃了2cpu

### ISSUE THREAD

**Issue by NikelChamp** [pythonzm/Ops#46]
同时跑两个脚本吃了2cpu, 峰值214%

**Comment by pythonzm** [comment]
额。。没遇到这情况，单独使用ansible命令执行没有问题么

**Comment by shean023** [comment]
- hosts: {{ host }}
  gather_facts: False
  connection: local

  tasks:

    - name: ping
      shell: ping -c 1 -w 2 192.168.238.129
      ignore_errors: true

==================================
playbook管理－－点击（操作）执行
- hosts: {{ host }}   这里应该 怎么填？
