### ISSUE TITLE
window rdp功能不够完善

### ISSUE THREAD

**Issue by tinson28** [pythonzm/Ops#47]
window rdp操作文件上传下载，还有本机和远程机器之间的复制黏贴没有实现，这块功能可以实现吗？

**Comment by Dreams-Jun** [comment]
我的rdp远程桌面一片空白  还没找到啥原因

**Comment by pythonzm** [comment]
@Dreams-Jun 看看你的guac进程正常不

**Comment by pythonzm** [comment]
@tinson28 这个需求有时间再搞吧

**Comment by Dreams-Jun** [comment]
正常的，进程在

发自我的 iPhone

**Comment by pythonzm** [comment]
@Dreams-Jun 确定远程主机开启了允许远程连接了么？rdp端口是否正确？
