### ISSUE TITLE
终端登录 10秒后会自动断开

### ISSUE THREAD

**Issue by fjmygame** [pythonzm/Ops#50]
这个要修改什么?

**Comment by pythonzm** [comment]
10秒？不应该，默认设置的3分钟，修改utils/ssh.py中的 self.chan.settimeout(60 * 3)，你把这个数值调大点儿试试

**Comment by fjmygame** [comment]
13:50:20] HTTP GET /assets/assets_list/ 2
13:50:20] HTTP GET /static/favicon.ico 20
13:50:21] HTTP GET /assets/ssh/1/ 200 [0.
13:50:21] WebSocket HANDSHAKING /ws/webss
13:50:21] WebSocket CONNECT /ws/webssh/1/
13:50:32] WebSocket DISCONNECT /ws/webssh
13:51:28] HTTP GET /assets/ssh/1/ 200 [0.
13:51:28] WebSocket HANDSHAKING /ws/webss
13:51:28] WebSocket CONNECT /ws/webssh/1/
13:51:39] WebSocket DISCONNECT /ws/webssh
settimeout 没有改

**Comment by fjmygame** [comment]
前端 关闭原因返回1011

**Comment by pythonzm** [comment]
自己修改了哪些内容？
