### ISSUE TITLE
做到第六步时候无法继续

### ISSUE THREAD

**Issue by peixiaoqing** [pythonzm/Ops#54]
楼主，你好呀，感谢在百忙中看这个问题，因为现在按照文档一路搭建下来，到达第6步得时候，启动服务报错找不到app指定的module，最后查看是配置文件那有个app地方需要指定，请问这个module是需要我们手动写吗？还是他官方有提供的默认模板？如果需要写能提供个模板吗？

**Comment by pythonzm** [comment]
你是说celery配置吗？现在的模板就是官网上的

**Comment by peixiaoqing** [comment]
> 
> 
> 你是说celery配置吗？现在的模板就是官网上的

楼主，你好，你帮我看下这个报错，还有配置是我哪有问题吗？我截图中有个框起来的，对这里不是太明白，我也看了官网给的说明也是不太明白，怎么使用这里
![图片](https://user-images.githubusercontent.com/35130532/70876450-97f33080-1ff4-11ea-9f63-1b523b4bfd15.png)
![图片](https://user-images.githubusercontent.com/35130532/70876464-a7727980-1ff4-11ea-8d65-d0e5ee3ea654.png)

**Comment by pythonzm** [comment]
这个CELERY_APP应该是在你的celery.py中指定的那个应用名字，比如我的是：
app = Celery('Ops', broker='redis://127.0.0.1:6379/0')
