### ISSUE TITLE
远程管理windows必须安装Guacamole？

### ISSUE THREAD

**Issue by grayflight** [pythonzm/Ops#60]
管理windows机器，收集windows主体信息，必须要安装Guacamole才行吗？

**Comment by pythonzm** [comment]
Guacamole是用于webssh的，如果只是手机主体信息就不需要

**Comment by grayflight** [comment]
在“资产列表”-收集windows的主体信息时报错：收集失败！> Failed to connect to the host via ssh: Connection timed out during banner exchange。这是怎么回事，windows也是基于ssh协议的吗？

**Comment by grayflight** [comment]
老哥您好，这个项目很好。我尝试了很多次配置Guacamole，但登录时总是“Invalid Login”，可以提供一份你的Guacamole配置手册吗？

**Comment by pythonzm** [comment]
> 老哥您好，这个项目很好。我尝试了很多次配置Guacamole，但登录时总是“Invalid Login”，可以提供一份你的Guacamole配置手册吗？

没有额外的配置，只需要按照官方的安装教程安装好就行了，你的guac服务正常启动了么？

**Comment by grayflight** [comment]
/etc/init.d/guacd status看是正常启动的，版本是0.9.14，不知道是否什么依赖包没安装？

**Comment by pythonzm** [comment]
是按照官网上的步骤安装的么？依赖包都装了么？你要远程的那台机器远程开了么？

**Comment by grayflight** [comment]
应该是我的OS环境问题，现在搞定了，多谢！
