### ISSUE TITLE
playbook管理界面，执行playbook的时候只能获取到定义到yaml文件中的主机名，无法获取到inventory主机组中的主机

### ISSUE THREAD

**Issue by lculiuyanlong** [pythonzm/Ops#63]
playbook管理界面，执行playbook的时候只能获取到定义到yaml文件中的主机名，无法获取到inventory主机组中的主机，
看ansible源代码中
pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
# FIXME: move out of inventory self._inventory.set_playbook_basedir(os.path.realpath(os.path.dirname(playbook_path)))

不知道self._inventory的值怎么传递进去？？？

**Comment by pythonzm** [comment]
我没太理解，一个playbook，不就是在指定主机上运行任务么？为啥要获取其他主机信息？
