### ISSUE TITLE
执行python3  manage.py makemigrations有错误提示，有人遇到这种情况？

### ISSUE THREAD

**Issue by zhengxuekang** [pythonzm/Ops#65]
You are trying to add the field 'add_time' with 'auto_now_add=True' to userplan without a default; the database needs something to populate existing rows.

**Comment by pythonzm** [comment]
把user相关表ops_user，ops_user_role，ops_users_plan删掉，然后将users/makemigrations目录下内容删掉，只保留__init__.py文件，再重新执行python3 manage.py makemigrations users
