### ISSUE TITLE
求教左侧栏菜单图标更改方式

### ISSUE THREAD

**Issue by binghu97** [pythonzm/Ops#74]
大神可否知道AdminLTE 前端框架下左侧新增菜单的菜单图标在哪里配置或者更改呢

**Comment by pythonzm** [comment]
首先把AdminLTE下载下来，它有一个页面专门记录的图标文件，找到你想要的图标，查看这个页面的源码找到对应的class，直接在主html文件中修改（我这里是base.html）就行，比如 `<li><a href="{% url 'inventory' %}"><i class="fa fa-gears"></i> 动态主机组</a></li>` 这里的 `fa-gears` 就是一个图标的class

**Comment by binghu97** [comment]
我试试，非常感谢作者解答。。

**Comment by binghu97** [comment]
作者是在上海么，加个好友把，空的话想选个时间请作者吃个饭表示感谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pythonzm"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 下午5:54
收件人: "pythonzm/Ops"<Ops@noreply.github.com&gt;; 
抄送: "冰蝴"<839571970@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pythonzm/Ops] 求教左侧栏菜单图标更改方式 (#74)





 
首先把AdminLTE下载下来，它有一个页面专门记录的图标文件，找到你想要的图标，查看这个页面的源码找到对应的class，直接在主html文件中修改（我这里是base.html）就行，比如 <li&gt;<a href="{% url 'inventory' %}"&gt;<i class="fa fa-gears"&gt;</i&gt; 动态主机组</a&gt;</li&gt; 这里的 fa-gears 就是一个图标的class

**Comment by pythonzm** [comment]
目前在北京，感谢支持 ：）
