### ISSUE TITLE
新增左侧菜单在右边区域不显示的问题

### ISSUE THREAD

**Issue by binghu97** [pythonzm/Ops#75]
求教 比如正常情况下，左边有项目列表，点击以后在右边也会出现，但是我搜索了，相关页面并没有直接写，现在我新增一个子菜单后，右边显示不了菜单名字，找了好久没有头绪，感觉和AdminLTE相关，但是找不到问题解决点在哪里。。还有右边那个Search:   show 功能也没了。。

**Comment by pythonzm** [comment]
没看懂。。左侧就是一个URL，右侧是渲染之后的template，一个请求抛去中间件的过程基本就是 
URL->View>template，Search: show 功能是啥，我咋没印象

**Comment by binghu97** [comment]
找到配置了，$(function ()定义了ajax
