### ISSUE TITLE
任务管理-执行模块 中点击执行有相同任务执行的

### ISSUE THREAD

**Issue by ljlj1986** [pythonzm/Ops#80]
就我一个人用,看到执行输出显示已经执行完成了，但是再次点击执行的时候就会出现有“有相同的任务正在进行！请稍后重试！”,怎么手动控制这个呢？

**Comment by pythonzm** [comment]
每一次执行任务都会先检查redis中有没有该任务的key，如果没有就新建一个然后执行任务，执行完毕后会删除这个key，如果有就会提示“有相同的任务正在进行！请稍后重试！” ，有改过redis的东西吗？

**Comment by ljlj1986** [comment]
谢谢，问题解决了，是跟redis配置相关，密码配置在项目迁移时遗漏了
