### ISSUE TITLE
关于playbook执行问题

### ISSUE THREAD

**Issue by zzjackaa** [pythonzm/Ops#85]
playbook测试
---
- hosts: test3
  tasks:
     - name: "helloworld"
       shell: echo "Hello World" `date` by `hostname` > /tmp/hello.log

这是两个主机组（都没有设置变量）

test | 192.168.40.14   192.168.40.13  192.168.40.15   192.168.40.17 |  

test3 | 192.168.40.13

这是结果  

开始执行....

PLAY [test3]************************************************************************************************************ 

PLAY RECAP *************************************************************************************************************

执行完毕....

我想说的是 这个主机组 是类似于ansible的hosts.ini文件还是要执行ansible的节点 就是这个django项目的主节点 我现在执行测试的playbook会显示这些 但是 并没有真的执行成功

**Comment by zzjackaa** [comment]
就好像没有hosts文件一样

**Comment by zzjackaa** [comment]
ansible-playbook  -i hosts.ini  /data/Ops-master/media/playbook/2020/7/2/abd.yml 这是我在您这个项目节点启动的playbook
测试是正常的 。求大佬解答谢谢

**Comment by pythonzm** [comment]
不需要hosts文件，主机组就是你的目标主机，需要提前在主机组中添加好，ansible主节点是这个系统所在的节点

**Comment by zzjackaa** [comment]
还有个问题大佬 
MySQL [ops]> select * from ops_ansible_module_log;
Empty set (0.00 sec)
我只成功了这个moudle 但是找不到日志 后来我去这个表中未发现数去插入
module_record.delay
看了下可能是celery的问题 但也找不到什么问题 因为ansible.log没有找到抛出的异常

后来发现后台启动后自己关闭了 而且没有log输出 虽说创建了log日志但是里面什么都没有 我是root起的
root@big02:/var/log/celery# /etc/init.d/celeryd start
celery init v10.1.
Using config script: /etc/default/celeryd
celery multi v4.2.0 (windowlicker)
> Starting nodes...
	> worker@big02: OK
root@big02:/var/log/celery# ps -aux |grep celery
root     312052 91.5  0.0 243860 89732 ?        R    16:52   0:01 /usr/bin/python3 -m celery worker --app=Ops --concurrency=8 --time-limit=300 --loglevel=INFO --logfile=/var/log/celery/worker%I.log --pidfile=/var/run/celery/worker.pid --hostname=worker@big02
root     312058  0.0  0.0  21312   940 pts/26   S+   16:52   0:00 grep --color=auto celery
root@big02:/var/log/celery# ps -aux |grep celery
root     312062  0.0  0.0  21312   944 pts/26   S+   16:52   0:00 grep --color=auto celery
root@big02:/var/log/celery# ls
beat.log  worker.log
root@big02:/var/log/celery# ls -l
总用量 0
-rw-r--r-- 1 root root 0 6月  23 10:22 beat.log
-rw-r--r-- 1 root root 0 6月  23 10:21 worker.log
root@big02:/var/log/celery#

**Comment by pythonzm** [comment]
如果使用root启动失败的话，先执行 `export C_FORCE_ROOT="true"` ，再使用 ` /etc/init.d/celeryd start` 启动

**Comment by zzjackaa** [comment]
[root@master Ops-master]# export C_FORCE_ROOT="true"
[root@master Ops-master]# /etc/init.d/celeryd start
celery init v10.1.
Using config script: /etc/default/celeryd
- Creating default directory: '/var/run/celery'
- Changing permissions of '/var/run/celery' to 02755
- Changing owner of '/var/run/celery' to 'root'
- Changing group of '/var/run/celery' to 'root'
celery multi v4.2.0 (windowlicker)
> Starting nodes...
	> workr@master: OK
 提示起来了 但是ps -aux |grep celery 的时候进程只有1s中就没了 log无输出 只有文件被创建

**Comment by zzjackaa** [comment]
手动执行 celery worker -A Ops.celery会报错 


 File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 673, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 683, in _autodiscover_tasks_from_fixups
    pkg for fixup in self._fixups
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 684, in <listcomp>
    for pkg in fixup.autodiscover_tasks()
AttributeError: 'NoneType' object has no attribute 'autodiscover_tasks'

**Comment by pythonzm** [comment]
celery的配置文件都配置的正确么
