### ISSUE TITLE
登录后报错

### ISSUE THREAD

**Issue by nondevops** [pythonzm/Ops#87]
环境:
mac/python3.6

报错详情:

Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.0.5
NoReverseMatch
Reverse for 'docker_list' not found. 'docker_list' is not a valid view function or pattern name.
/Users/tanjiangfu/.pyenv/versions/ops/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 632
/Users/tanjiangfu/.pyenv/versions/ops/bin/python
3.6.6
['/Users/tanjiangfu/.pyenv/versions/ops/lib/python3.6/site-packages/git/ext/gitdb',  '/Users/tanjiangfu/github.com/Ops',  '/Users/tanjiangfu/.pyenv/versions/ops/lib/python36.zip',  '/Users/tanjiangfu/.pyenv/versions/ops/lib/python3.6',  '/Users/tanjiangfu/.pyenv/versions/ops/lib/python3.6/lib-dynload',  '/Users/tanjiangfu/.pyenv/versions/3.6.6/lib/python3.6',  '/Users/tanjiangfu/.pyenv/versions/ops/lib/python3.6/site-packages',  '/Users/tanjiangfu/github.com/Ops',  '/Users/tanjiangfu/.pyenv/versions/ops/lib/python3.6/site-packages/gitdb/ext/smmap']
Mon, 20 Jul 2020 16:24:37 +0800

截图:
![image](https://user-images.githubusercontent.com/12181410/87916218-bb5bed80-caa5-11ea-91f8-f9fa34329757.png)

@pythonzm 麻烦看看呢

**Comment by ZhaoFan777** [comment]
请问这个问题是怎么解决的
