### ISSUE TITLE
ws问题

### ISSUE THREAD

**Issue by NikelChamp** [pythonzm/Ops#9]
大佬，请教ws出现404一般是什么原因呢？
```
General
    Request URL: ws://172.31.8.129:8000/ws/ans_module_log/
    Request Method: GET
    Status Code: 404 Not Found
```
```
failed: Error during WebSocket handshake: Unexpected response code: 404
```

**Comment by pythonzm** [comment]
404是找不到资源，做什么操作报的错？

**Comment by NikelChamp** [comment]
> 404是找不到资源，做什么操作报的错？

找到原因了
```
uwsgi --http 0.0.0.0:8000 --file Ops/wsgi.py --static-map=/static=static 
```
我用这个命令启动的时候就会这样，
```
python manage.py runserver 0.0.0.0:8000
```
这个python命令直接启动没问题，请问这两个有什么区别么，是不是uwsgi还要指定一下socket什么的？

**Comment by pythonzm** [comment]
直接用runserver启动，如果settings.py设置DEBUG为False的话，就不会加载静态文件，要想加载的话需要添加参数--insecure，而且这种启动方式不能保证性能，但是可以直接处理websocket；uwsgi启动不能处理websocket请求，需要单独给websocket开端口。建议多看官网

**Comment by NikelChamp** [comment]
--insecure这个我知道，只是不太了解uwsgi，谢谢大佬解惑。对了大佬，主机组变量配置那里再加一层包裹主机组是不是就不用修改playbook了？

**Comment by pythonzm** [comment]
确切的说uwsgi目前不支持channels，如果使用其他方式编写websocket，有可能采用uwsgi启动没有问题，我没有测试

**Comment by NikelChamp** [comment]
大佬，其实一直有一个问题想问，如果我一个playbook在执行中，还能马上再接着执行另一个playbook么？

**Comment by pythonzm** [comment]
如果一个playbook执行时间过长，只能新打开一个标签页执行其他任务，有啥好的建议吗？

**Comment by NikelChamp** [comment]
可不敢乱给大佬建议，其实还有几个问题憋了好久想问大佬
```
playbook要随着组名的变更而修改这个好像有点麻烦，如果可以在用户组上再包装一层，就可以不用修改playbook的组名了？

再一个是如果不小心关闭了浏览器，playbook状态是终止了执行还是仍然执行，是不是可以找回进度？

还有redis锁，如果服务挂了，执行的playbook锁死，只能改名，那么每次启动服务都flush一次redis会更好一点？
```
因为我一直想着改改看，可是自己技术不够，也不敢胡乱改大佬的代码，再次膜拜大佬的技术，请收下膝盖

**Comment by pythonzm** [comment]
1、这个不太确定能不能实现，得看看ansible官网，话说主机组为什么会经常变动？
2、关闭浏览器playbook还是会继续执行，重新找回进度这个需求不好说，得查查相关资料
3、服务挂了啥意思？Ops系统直接挂了么？

我想着是在playbook执行界面加一个选项，选择是否实时显示结果，选择否就直接后台运行，然后显示一个大概进度，只是这个进度显示一直没想明白要怎么弄。

我也不是大佬，你自己写多了，就会发现我写的代码很low的（＃－.－）

**Comment by NikelChamp** [comment]
> 1、这个不太确定能不能实现，得看看ansible官网，话说主机组为什么会经常变动？
> 2、关闭浏览器playbook还是会继续执行，重新找回进度这个需求不好说，得查查相关资料
> 3、服务挂了啥意思？Ops系统直接挂了么？
> 
> 我想着是在playbook执行界面加一个选项，选择是否实时显示结果，选择否就直接后台运行，然后显示一个大概进度，只是这个进度显示一直没想明白要怎么弄。
> 
> 我也不是大佬，你自己写多了，就会发现我写的代码很low的（＃－.－）

你很厉害了，反正我很佩服的。关于昨天的问题可能我表达不是很清楚

1.我的意思是如果我想复用同一个playbook，比如安装nginx, 分别是两个不同的组A 和 B需要安装，按照现在的办法就是需要两套playbook, 而区别仅仅是hosts的不同，如果不想同时存在两个区别不大的playbook，那就只能是修改playbook的hosts。就算hosts写死A，B，但如果临时添加组C, 那么还是需要修改playbook来添加组C, 不知道我这样表达清晰么？

2.重新找回进度就是因为不知道关闭浏览器之后playbook是的状态，如果能够有一个页面显示已完成和进行中应该会更好？

3 .Ops系统直接挂了, 然后就锁死了，我尝试过在manage.py加上清空redis的操作，就是每次启动就会flushdb()一次，很暴力，不知道对其他功能有没有影响。

另外昨天大佬你说的同时执行ansible任务这个，是不是可以做成一个执行按钮，点击之后跳出小页面，小页面有添加一组按钮，选中主机组，选中playbook，如果再想同时执行多个ansible任务，就点击添加，再选中主机和playbook，不知道我这个想法是不是太天真了些

**Comment by pythonzm** [comment]
1、既然AB两个组执行同一个任务，你直接在hosts那儿同时指定这两个组不就好了，为啥还要弄两个playbook？
2、现在已经有已完成的执行日志了，再弄一个页面显示正在执行的任务和已完成的任务感觉重复了，我觉得在执行页面加一个正在执行任务的进度显示比较好
3、没必要每次启动都刷新key，你把key设置一个超时时间就好了，而且我觉得Ops系统挂的几率应该不是很大吧。。。

动态的去选择playbook和主机组对于一个playbook中只包含一个组的情况好实现，但是如果一个playbook中同时有多个组执行多个任务的情况，我觉得在playbook中直接指定组更方便
